export { default as iconChat } from "./chat.svg"
export { default as iconExit } from "./exit.svg"
export { default as iconSettings } from "./settings.svg"
export { default as iconClose } from "./close.svg"
export { default as iconCamera } from "./camera.svg"
export { default as iconMicrophone } from "./microphone.svg"
export { default as iconLogo } from "./logo.svg"
export {default as iconTile} from "./tile.svg"
export {default as iconRecordStart} from "./recordStart.svg"
export {default as iconRecordStop } from "./recordStop.svg"

